
# Compiler settings

UNAME := $(shell uname)

ifeq ($(UNAME),Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -O3 -DNDEBUG
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME),Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall -Wno-unknown-pragmas
  CXXFLAGS += -O3 -DNDEBUG
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifneq ($(CLANG), LLVM)
    CXXFLAGS += -fopenmp
    #CXXOPENMP += -fopenmp
  else
    CXXFLAGS += -DNOMP
    CXXOPENMP =
  endif
  LDFLAGS +=
  LIBS +=

endif


# Directories ---

SNAPDIR = ../../snap-core
GLIBDIR = ../../glib-core
AGMDIR = ../../snap-adv

BINDIR = bin

# Compiled Libraries ---

SNAPLIB = $(SNAPDIR)/Snap.o


# BigClam-related ---

BIGCLAM_CORE_O = $(BINDIR)/agm.o \
                 $(BINDIR)/agmfit.o 

BIGCLAM_DEP_O = $(BIGCLAM_CORE_O) \
                $(BINDIR)/agmfast.o 
BIGCLAM_OLD_DEP_O = $(BIGCLAM_CORE_O) \
                    $(BINDIR)/agmfast_old.o 

BIGCLAM_HEADERFLAGS = -I. \
                      -I$(SNAPDIR) \
                      -I$(GLIBDIR) \
                      -I$(AGMDIR) 
