
# Compiler settings (assume it is run under Linux environment) ---

CC = g++
CXXFLAGS += -std=c++11 -Wall
CXXFLAGS += -O3 -DNDEBUG -pthread
CXXOPENMP = -fopenmp
LDFLAGS +=
LIBS += -lrt


# Directories ---

SNAPDIR = ../../snap-core
GLIBDIR = ../../glib-core
AGMDIR = ../../snap-adv

BINDIR = bin

# Compiled Libraries ---

SNAPLIB = $(SNAPDIR)/Snap.o


# BigClam-related ---

BIGCLAM_CORE_O = $(BINDIR)/agm.o \
                 $(BINDIR)/agmfit.o 

BIGCLAM_DEP_O = $(BIGCLAM_CORE_O) \
                $(BINDIR)/agmfast.o 
BIGCLAM_OLD_DEP_O = $(BIGCLAM_CORE_O) \
                    $(BINDIR)/agmfast_old.o 

BIGCLAM_HEADERFLAGS = -I. \
                      -I$(SNAPDIR) \
                      -I$(GLIBDIR) \
                      -I$(AGMDIR) 
