#
#	Makefile for this SNAP example
#	- modify Makefile.ex when creating a new SNAP example
#
#	implements:
#		all (default), clean
#

include ../../Makefile.config
include Makefile.ex

# it requires shared libraries, so the common example Makefile is not used
include ../Makefile.exmain

