#
# Makefile for non-Microsoft compilers
#

all: MakeAll

MakeAll:
	$(MAKE) -C agmgen
	$(MAKE) -C agmfit
	$(MAKE) -C bigclam
	$(MAKE) -C cascades
	$(MAKE) -C centrality
	$(MAKE) -C cesna
	$(MAKE) -C circles
	$(MAKE) -C cliques
	$(MAKE) -C coda
	$(MAKE) -C community
	$(MAKE) -C concomp
	$(MAKE) -C flows
	$(MAKE) -C forestfire
	$(MAKE) -C graphgen
	$(MAKE) -C graphhash
	$(MAKE) -C infopath
	$(MAKE) -C kcores
	$(MAKE) -C kronem
	$(MAKE) -C krongen
	$(MAKE) -C kronfit
	$(MAKE) -C magfit
	$(MAKE) -C maggen
	$(MAKE) -C mkdatasets
	$(MAKE) -C motifs
	$(MAKE) -C ncpplot
	$(MAKE) -C netevol
	$(MAKE) -C netinf
	$(MAKE) -C netstat
	$(MAKE) -C testgraph

clean:
	$(MAKE) clean -C agmgen
	$(MAKE) clean -C agmfit
	$(MAKE) clean -C bigclam
	$(MAKE) clean -C cascades
	$(MAKE) clean -C centrality
	$(MAKE) clean -C cesna
	$(MAKE) clean -C circles
	$(MAKE) clean -C cliques
	$(MAKE) clean -C coda
	$(MAKE) clean -C community
	$(MAKE) clean -C concomp
	$(MAKE) clean -C flows
	$(MAKE) clean -C forestfire
	$(MAKE) clean -C graphgen
	$(MAKE) clean -C graphhash
	$(MAKE) clean -C infopath
	$(MAKE) clean -C kcores
	$(MAKE) clean -C kronem
	$(MAKE) clean -C krongen
	$(MAKE) clean -C kronfit
	$(MAKE) clean -C magfit
	$(MAKE) clean -C maggen
	$(MAKE) clean -C mkdatasets
	$(MAKE) clean -C motifs
	$(MAKE) clean -C ncpplot
	$(MAKE) clean -C netevol
	$(MAKE) clean -C netinf
	$(MAKE) clean -C netstat
	$(MAKE) clean -C testgraph
	rm -rf Debug Release ipch
